<?php
/**
 * @file
 * Custom functionality for a wind farm database.
 */

/**
 * Implements hook_node_view().
 */
function jobposition_node_view($node, $view_mode, $langcode) {

  if ($node->type == 'positions' && $view_mode == 'full') {


      if (!function_exists('node_add')) {
        module_load_include('inc', 'node', 'node.pages');
      }

      $positions = node_add('positions');

      //  print '<pre>';
      // var_dump($positions);
      // print '<pre>';

      unset($positions->field_cv);


      $node->content['my_additional_field'] = array(
    '#markup' => drupal_render($positions),
    '#weight' => 10,

  );


      //return print drupal_render(node_add('positions'));
      // print '<pre>';
      // var_dump($node);
      // print '<pre>';

      // exit();
      // $form = drupal_get_form('example_module_form', $node);

      // $node->content['data_collection_form'] = array(
      //   '#markup' => drupal_render($form),
      //   '#weight' => 10,
      // );

    // $form = node_add('positions');
    // var_dump($form);
    //return drupal_render($form);


      // $node->content['my_additional_field'] = array(
  //   '#markup' => $additional_field,
  //   '#weight' => 10,
  //   '#theme' => 'mymodule_my_additional_field',
  // );

  }





}
